trigger:
- master

pool:
  vmImage: ubuntu-latest



steps:
    - task: CmdLine@2
      continueOnError: true
      inputs:
      
        script: |
          ls -ltr
          pwd
          docker run -v /home/vsts/work/1/s/collections:/temp/test -t justb4/jmeter -Jthreads=10 -Jrampup=20 -n -t /temp/test/DemoPET.jmx -l /temp/test/log.jtl
          -e -o /temp/test/html/10VuReport
          ls -ltr collections
          
    - task: PublishTestResults@2
      displayName: 'Publish Test Results for Jmeter'
      inputs:
       testResultsFormat: 'JUnit'
       searchFolder: '$(System.DefaultWorkingDirectory)'
       testResultsFiles: '/temp/test/index.html'      
       mergeTestResults: true
       failTaskOnFailedTests: false
       
        