trigger:
- master

pool:
  vmImage: ubuntu-latest



steps:
    - task: CmdLine@2
      continueOnError: true
      inputs:
      
        script: |
          ls -ltr
          pwd
          docker run -v /home/vsts/work/1/s/collections:/temp/test -t justb4/jmeter -Jthreads=10 -Jrampup=20 -n -t /temp/test/DemoPET.jmx -l /temp/test/log.jtl -e -o /temp/test/report 
          docker -v /home/vsts/work/_tasks/results :/collections/report
          ls -ltr collections
          ls -ltr /home/vsts/work/_tasks
          ls -ltr /home/vsts/work/1/s
  
    
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)/s/collections/report'
        publishLocation: 'pipeline'
    - task: publishhtmlreport@1
      inputs:
        htmlType: 'Jmeter'
        JmeterReportsPath: '$(Pipeline.Workspace)/s/collections/report'  
          
    - task: CalromEmailReport@1
      inputs:
        sendMailConditionConfig: 'Always'
        subject: '[{environmentStatus}] {passPercentage} tests passed in $(Release.EnvironmentName) stage for $(Build.BuildNumber)'
        toAddress: 'ram0309m@gmail.com'
        defaultDomain: 'xxxxxxx.com'
        groupTestResultsBy: 'run'
        includeCommits: false
        maxTestFailuresToShow: '15'
        includeOthersInTotal: true
        usePreviousEnvironment: false