trigger:
- master

pool:
  vmImage: ubuntu-latest



steps:
    - task: CmdLine@2
      continueOnError: true
      inputs:
      
        script: |
          ls -ltr
          pwd
          docker run -v /home/vsts/work/1/s/collections:/etc/postman -t justb4/jmeter -n -t DemoPET.jmx -l log.jtl --reporters cli,junit --reporter-junit-export /etc/postman/junit-report.xml
          ls -ltr collections
          
    - task: PublishTestResults@2
      displayName: 'Publish Test Results for postman'
      inputs:
       testResultsFormat: 'JUnit'
       searchFolder: '$(System.DefaultWorkingDirectory)'
       testResultsFiles: '$(Build.SourcesDirectory)/TestFiles/LoadReports/Junit.xml'      
       mergeTestResults: true
       failTaskOnFailedTests: false
       
        