trigger:
- master

pool:
  vmImage: ubuntu-latest



steps:
    - task: CmdLine@2
      continueOnError: true
      inputs:
      
        script: |
          ls -ltr
          pwd
          docker run -v /home/vsts/work/1/s/collections:/temp/test -t justb4/jmeter -Jthreads=10 -Jrampup=20 -n -t /temp/test/DemoPET.jmx -l /temp/test/log.jtl -e -o /temp/test/report 
          ls -ltr collections
          ls -ltr /home/vsts/work/1/s
          pwd
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/TEST-*.xml'
          
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/*.xml'
        searchFolder: '**'
        mergeTestResults: true
        failTaskOnFailedTests: true
    
       
        