trigger:
- master

pool:
  vmImage: ubuntu-latest



steps:
    - task: CmdLine@2
      continueOnError: true
      inputs:
      
        script: |
          ls -ltr
          pwd
          docker run -v /home/vsts/work/1/s/collections:/temp/test -t justb4/jmeter -Jthreads=10 -Jrampup=20 -n -t /temp/test/DemoPET.jmx -l /temp/test/log.jtl -e -o /home/vsts/work/_tasks/report 
          ls -ltr collections
          ls -ltr /home/vsts/work/_tasks
          ls -ltr /home/vsts/work/1/s

    - task: publishhtmlreport@1
      inputs:          
        htmlType: 'genericHTML'
        htmlPath: '$(Build.SourcesDirectory)/Sample.html'     
    
        